language: python
dist: xenial
python:
- '3.7'
- '3.6'
- '3.5'
- '2.7'
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: gusennan
  password:
    secure: VN2f9Q6wsObabHSJdiaemaptmAf+RY43nIFrErnoAb+tcL95BgSAu7HrzQRrkLEk5nUCKSPmKgfZEssRfQLsHzjOSHdkj6opMkm3LBr54OOs9AfbTPXFsJs20E/hPOS76EJhibdeEzUUiucnc8nmwLVBIZNBsJVr5ivM5XIMJMV5ePf7kxO42aFjCtCPjZPhO8iU+9BU/nI3wdGRpmXNHGOGYhrrNbbC5hFLXxuserv3YYepHEycSTyFl9aJhnmLX57Fy3vNSN5Or9JcXCJ4ynrWQIwpXMfnU9FnUEObI2fnlF8+eDsJvnyiS9Edj3J/N8uQMkuP7Fw9z1cRdLmcL8MJDQ/NPSVpqHSyfLRHd/yUkv2wVl1ndDyj3EFQcL9thFYFECjc8vseBL0e5Tt/Mp+yFH94/C+CDRcxVahyIfzl5bhY2U5CsdCbh+eUG7XDoX614HA39bnuAX9qJo8+nKaVc56mOcn4qmVwg7xa+u0kRSR42vxKi8tfWEP7jcWzfPWzDoZasqMnFbDzXFKRE1Rj7Oq1J2cajqmBBy7rPob8aI0LO65+/lwnQWvFWhH12xjbkoKdp5z5y8sES2TfJ6ZABnv30foBDkU0pjKErcc+WinG9JNw64WmpLGOrrMUlcuFB5NHHE91z3sTf37pXRIdW+fEJKahnQRYI9+/Wuo=
  on:
    tags: true
    repo: gusennan/libprot
    python: 3.7
